[package]
authors = ["killzoner"]
edition = "2024"
name = "cargo-neat"
resolver = "3"
version = "0.5.2"

description = "Keep your cargo workspace neat: find unused dependencies and enforce workspace consistency"
documentation = "https://docs.rs/cargo-neat"
keywords = ["cargo", "dependencies", "workspace", "lint"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/killzoner/cargo-neat"

[dependencies]
anyhow = { version = "1.0.102", default-features = false }
argh = { version = "0.1.19", default-features = false, features = ["help"] }
cargo = { version = "0.98.0", default-features = true }
log = { version = "0.4.32", default-features = false }
pretty_env_logger = { version = "0.5.0", default-features = false }
termtree = { version = "1.0.0", default-features = false }

[dev-dependencies]
trycmd = { version = "1.2.0", default-features = false, features = [
  "color-auto",
  "diff",
] }

[features]
default = []

cargo-static = ["cargo/all-static"]

# optimized cargo wizard profile for MinSize
[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
