name: continuous-integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER: ""

jobs:
  # act -P ubuntu-latest=-self-hosted -j build
  build:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Install musl tools
        run: sudo apt install -y musl-tools
      - run: cargo build --all --all-targets --all-features --target x86_64-unknown-linux-musl
  lint:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-lint-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
        with: 
          components: clippy
      - run: cargo clippy --all --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: cargo machete
  test:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-test-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-expand
      - run: cargo test
  fmt:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-fmt-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
        with: 
          components: rustfmt
      - run: cargo fmt --all
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - name: Run cargo sort
        run : taplo format
      - name: Check for a diff
        run: git diff --exit-code
  cargo-deny-checks:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-cargo-deny-checks-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - name: cargo deny
        run: cargo deny -L error --workspace check bans advisories sources
  install-action-check:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-install-action-check-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-neat
      - working-directory: integration-tests/clean
        run: cargo neat -m -p -f
      - run: cargo neat -f
